services:
  db:
    image: postgres:16-alpine
    container_name: cyber_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: cyber_protection_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: cyber_backend
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgrespassword@db:5432/cyber_protection_db
      - OLLAMA_URL=http://host.docker.internal:11434
    extra_hosts:
      - "host.docker.internal:host-gateway"   # inofensivo en Windows, necesario si algún día corren en Linux
    depends_on:
      - db

volumes:
  postgres_data: